CREATE TYPE STATUS AS ENUM('UNKNOWN', 'PENDING', 'PARSING_FAILED', 'TRANSPORT_FAILED');

CREATE TABLE detection_status (
    request_id UUID PRIMARY KEY,
    status STATUS NOT NULL,
    data BYTEA
);
