// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("DetectionStatuses", testDetectionStatuses)
}

func TestDelete(t *testing.T) {
	t.Run("DetectionStatuses", testDetectionStatusesDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("DetectionStatuses", testDetectionStatusesQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("DetectionStatuses", testDetectionStatusesSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("DetectionStatuses", testDetectionStatusesExists)
}

func TestFind(t *testing.T) {
	t.Run("DetectionStatuses", testDetectionStatusesFind)
}

func TestBind(t *testing.T) {
	t.Run("DetectionStatuses", testDetectionStatusesBind)
}

func TestOne(t *testing.T) {
	t.Run("DetectionStatuses", testDetectionStatusesOne)
}

func TestAll(t *testing.T) {
	t.Run("DetectionStatuses", testDetectionStatusesAll)
}

func TestCount(t *testing.T) {
	t.Run("DetectionStatuses", testDetectionStatusesCount)
}

func TestHooks(t *testing.T) {
	t.Run("DetectionStatuses", testDetectionStatusesHooks)
}

func TestInsert(t *testing.T) {
	t.Run("DetectionStatuses", testDetectionStatusesInsert)
	t.Run("DetectionStatuses", testDetectionStatusesInsertWhitelist)
}

func TestReload(t *testing.T) {
	t.Run("DetectionStatuses", testDetectionStatusesReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("DetectionStatuses", testDetectionStatusesReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("DetectionStatuses", testDetectionStatusesSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("DetectionStatuses", testDetectionStatusesUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("DetectionStatuses", testDetectionStatusesSliceUpdateAll)
}
