version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP protocol
      - "15672:15672"    # RabbitMQ Management UI
    networks:
      - mango-net
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    image: mango-truth-core:1.0.0
    container_name: core
    ports:
      - "8080:8080"
    environment:
      COMPUTE_HOST: rabbitmq
      POSTGRES_USER: mango-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mango-db
    networks:
      - mango-net
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8080/api/"]
#      interval: 30s
#      timeout: 10s
#      retries: 3

  front-end:
    build:
      context: ./frontend            # Set build context to front-end directory
      dockerfile: Dockerfile         # Dockerfile is located within front-end/
    image: front-end-mango-truth
    container_name: front-end-mango-truth
    ports:
      - "7860:7860"
    environment:
      GRADIO_SERVER_NAME: "0.0.0.0"
      GRADIO_SERVER_PORT: 7860
      SERVER_URL: "http://core:8080"
    networks:
      - mango-net
    depends_on:
      core:
        condition: service_started
      #        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    #        condition: service_healthy
    #    healthcheck:
    #      test: ["CMD", "curl", "-f", "http://localhost:7860"]
    #      interval: 30s
    #      timeout: 10s
    #      retries: 3
    extra_hosts:
      - "host.docker.internal:host-gateway"

  compute:
    build:
      dockerfile: ./compute/Dockerfile
    image: mango-truth-compute:1.0.0
    container_name: compute
    environment:
      RABBITMQ_HOST: rabbitmq
      POSTGRES_DB: mango-db
      POSTGRES_USER: mango-user
      POSTGRES_PASSWORD: password
      NEPTUNE_TOKEN:
    networks:
      - mango-net
    depends_on:
      rabbitmq:
        condition: service_healthy


  postgres:
    ports:
      - "5432:5432"
    build:
      context: ./core/pkg/storage/docker
      dockerfile: Dockerfile
    networks:
      - mango-net
    container_name: postgres
    image: postgres:16.4
    environment:
      POSTGRES_USER: mango-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mango-db
    volumes:
     - storage:/var/lib/postgresql/data


networks:
  mango-net:
    driver: bridge


volumes:
  storage:
    external: true