rabbitmq:
  source_queue_name: "request_queue"
  response_queue_name: "response_queue"
  host: "localhost"
  port: 5672
  username: "guest"
  password: "guest"
detectors:
  postgres_db: "mango-truth"
  postgres_user: "postgres"
  postgres_password: "postgres"
