name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_and_build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subproject: [ frontend, compute, detectors, core ]
    env:
      PYTHON_VERSION: 3.11
      GO_VERSION: 1.23

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.subproject }}
        if: matrix.subproject != 'core'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache Python dependencies
        if: matrix.subproject != 'core'
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
          key: python-${{ matrix.subproject }}-${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            python-${{ matrix.subproject }}-${{ runner.os }}-pip-

      - name: Install Python dependencies
        if: matrix.subproject != 'core'
        run: |
          pip install -r ${{ matrix.subproject }}/requirements.txt

      - name: Set up Go for core
        if: matrix.subproject == 'core'
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        if: matrix.subproject == 'core'
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-mod-${{ matrix.subproject }}-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod-${{ matrix.subproject }}-${{ runner.os }}-

      - name: Build go subproject
        if: matrix.subproject == 'core'
        run: |
          cd ./core
          go build ./cmd/server
      - name: Build python subproject
        if: matrix.subproject != 'core'
        run: echo "No build step required for ${{ matrix.subproject }}"

      - name: Run GO tests for ${{ matrix.subproject }}
        if: matrix.subproject == 'core'
        run: |
          cd ./core
          go test ./core/tests/
      - name: Run Python tests for ${{ matrix.subproject }}
        if: matrix.subproject != 'core'
        run: python -m pytest ${{ matrix.subproject }}/tests/
