name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.11
      GO_VERSION: 1.23
    strategy:
      matrix:
        subproject: [frontend, compute, models, core]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.subproject }}
        if: matrix.subproject != 'core'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies for ${{ matrix.subproject }}
        if: matrix.subproject != 'core'
        run: |
          pip install -r ${{ matrix.subproject }}/requirements.txt

      - name: Set up Go for core
        if: matrix.subproject == 'core'
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Go dependencies for core
        if: matrix.subproject == 'core'
        run: |
          go mod download

  build:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.11
      GO_VERSION: 1.20
    strategy:
      matrix:
        subproject: [frontend, compute, models, core]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.subproject }}
        if: matrix.subproject != 'core'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build ${{ matrix.subproject }}
        if: matrix.subproject != 'core'
        run: |
          echo "No build step required for ${{ matrix.subproject }}"

      - name: Set up Go for core
        if: matrix.subproject == 'core'
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build core
        if: matrix.subproject == 'core'
        run: |
          go build ./core/main

  test:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.11
      GO_VERSION: 1.20
    strategy:
      matrix:
        subproject: [frontend, compute, models, core]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.subproject }}
        if: matrix.subproject != 'core'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Run tests for ${{ matrix.subproject }}
        if: matrix.subproject != 'core'
        run: |
          python -m pytest ${{ matrix.subproject }}/tests/

      - name: Set up Go for core
        if: matrix.subproject == 'core'
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests for core
        if: matrix.subproject == 'core'
        run: |
          go test ./core/tests/
