name: Deploy to EC2 on Release Branch Commit

on:
  push:
    branches:
      - 'release-*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read and Initialize Version
        id: get_version
        run: |
          if [ ! -f VERSION ]; then echo "0.0.1" > VERSION; fi
          echo "Current version: $(cat VERSION)"
          echo "version=$(cat VERSION)" >> $GITHUB_ENV

      - name: Increment Version
        id: increment_version
        run: |
          # Read the current version and split it into major, minor, and patch parts
          version=$(cat VERSION)
          IFS='.' read -r -a parts <<< "$version"

          # Handle cases where VERSION might be malformed or empty
          if [ "${#parts[@]}" -ne 3 ]; then
            echo "0.0.1" > VERSION
          else
            # Increment the patch version
            parts[2]=$((parts[2] + 1))
            new_version="${parts[0]}.${parts[1]}.${parts[2]}"
            echo $new_version > VERSION
          fi

          echo "New version: $(cat VERSION)"
          echo "new_version=$(cat VERSION)" >> $GITHUB_ENV

      - name: Commit new version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add VERSION
          git commit -m "Bump version to ${{ env.new_version }}"
          git push origin HEAD:${{ github.ref }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ./MangoTruth
            sudo systemctl stop mango-truth
            git pull origin ${{ github.ref }}
            sudo systemctl start mango-truth
